sudo: false
language: node_js
node_js:
  - '10'

cache:
  directories:
  - "$HOME/.npm"

env:
  global:
    - GITHUB_REPO: 'alajfit/vuex-action-patcher'

branches:
  only:
    - master

stages:
  - test
  - documentation

jobs:
  include:
    - stage: test
      name: 'Test ➔ Lint'
      install: travis_wait npm ci --verbose
      script: npm run lint
    - name: 'Test ➔ Unit'
      install: 
        - travis_wait npm ci --verbose
        - npm install -g codecov
      script: 
        - npm run test
        - codecov
    - name: 'Test ➔ Build'
      install: travis_wait npm ci --verbose
      script: npm run build

    - stage: documentation
      name: 'Documentation ➔ Deploy'
      install: travis_wait npm ci --verbose
      script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - git config --global github.token $GITHUB_TOKEN
        - npm run docs:build
        - npm run docs:deploy