sudo: false
language: node_js
node_js:
  - '10'

cache:
  directories:
  - "$HOME/.npm"

env:
  global:
    - GITHUB_REPO: 'alajfit/vuex-action-patcher'

branches:
  only:
    - master

stages:
  - test

jobs:
  include:
    - stage: test
      name: 'Test ➔ Lint'
      install: travis_wait npm ci --verbose
      script: npm run lint